### ISSUE TITLE
Duplicate "Update Totals" button directly above the Totals column

### ISSUE THREAD

**Issue by SchalkCloete** [SINTEF/Scale-Coupled-Open-Innovation-Network#2]
It's not so intuitive to see that one should click the Update Totals button at the bottom of the CAPEX sheet. Can you put a copy of the button also directly above the Totals column? That would make it more intuitive.

**Comment by SchalkCloete** [comment]
Please also fix the small typo in cell X36 in the Plant Overview sheet.

**Comment by carnaiz88** [comment]
> It's not so intuitive to see that one should click the Update Totals button at the bottom of the CAPEX sheet. Can you put a copy of the button also directly above the Totals column? That would make it more intuitive.

The macros of both CFA and SA have been modified to automatically update totals of the CAPEX sheet in each run to avoid wrong calculations taking place. But I think it is more intuitive indeed to have the update macros in a more visible region.

**Comment by carnaiz88** [comment]
> Please also fix the small typo in cell X36 in the Plant Overview sheet.

Fixed.
